name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy Environment'
	required: true
	default: 'staging'
 	type: choice
  	options:
   	  - staging
      	  - production
      version:
        description: 'Version tag'
	required: false
 	type: string
