name: manual-run-example-2
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        required: true
        default: 'staging'
      version:
        description: 'Version tag'
        required: false
